#!/bin/bash

set -e
set -x

function missing_dep {
  echo "Missing dependency: $1, exting now!"
  exit 1
}

command -v feh || missing_dep "feh"
command -v scrot || missing_dep "scrot"
command -v mogrify || missing_dep "mogrify (from imagemagick)"

cp -s $(pwd)/bin/scrot-service-read ~/.local/bin/

mkdir -p ~/.local/systemd-bin/
mkdir -p ~/.config/systemd/user/

# systemd does not like symlinks
cp -l $(pwd)/bin/scrot-service-run ~/.local/systemd-bin/

cp $(pwd)/.config/systemd/user/scrot.service  ~/.config/systemd/user/

systemctl --user daemon-reload
systemctl --user start scrot.service
systemctl --user enable scrot.service

journalctl --user-unit scrot.service --since today -f
